apiVersion: v1
kind: Service
metadata:
  name: petpulse-network
spec:
  type: ClusterIP
  selector:
    app: petpulse-server
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
