apiVersion: apps/v1
kind: Deployment
metadata:
  name: petpulse-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petpulse-server
  template:
    metadata:
      labels:
        app: petpulse-server
    spec:
      containers:
        - name: server
          image: "{{IMAGE_REPO}}/petpulse-server:latest"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: petpulse-config
            - secretRef:
                name: petpulse-secrets
          # env:
          #   - name: GOOGLE_APPLICATION_CREDENTIALS
          #     value: /app/secrets/credentials.json
          # volumeMounts:
          #   - name: gcp-creds
          #     mountPath: /app/secrets
          #     readOnly: true
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      # volumes:
      #   - name: gcp-creds
      #     secret:
      #       secretName: petpulse-gcp-creds
